modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "extralib"
version = "${project_version}"
displayName = "${project_name}"
logoFile = "logo.png"
authors = "Vecoo"
description = "Library for mods."

[[dependencies.extralib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extralib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"